version: '3.8'

services:
  employee-service:
    image: mysql:8.0
    container_name: employeeservice_db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: employeeservice_db
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - employee_db_data:/var/lib/mysql

  department-service:
    image: mysql:8.0
    container_name: departmentservice_db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: departmentservice_db
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - department_db_data:/var/lib/mysql

  organization-service:
    image: mysql:8.0
    container_name: organizationservice_db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: organizationservice_db
    ports:
      - "3308:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - organization_db_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "15672:15672"  # Management console
      - "5672:5672"    # AMQP protocol port

volumes:
  employee_db_data:
  department_db_data:
  organization_db_data:
